#!/bin/bash

# Inspired by https://github.com/zaiste/docker-postgresql

# TODO replace this with a trap 
set -e

PG_DATADIR=/var/lib/pgsql/data
PG_BINDIR=/usr/pgsql-9.3/bin

if [ ! -d $PG_DATADIR ]; then
    mkdir -p $PG_DATADIR
    chown -R postgres:postgres $PG_DATADIR
    su - postgres -c "/usr/pgsql-9.3/bin/initdb -D $PG_DATADIR"

    # Allow all logins from the brigde, using a password
    echo "host    all             all             172.17.42.1/32            md5" >> $PG_DATADIR/pg_hba.conf
    
    # Listen for connections on all interfaces
    echo "listen_addresses='*'" >> $PG_DATADIR/postgresql.conf

    # Set a password for postgres user to allow remote connections
    su - postgres -c "$PG_BINDIR/postgres --single -D $PG_DATADIR" <<< "ALTER USER postgres with password 'password';"
fi

su - postgres -c "$PG_BINDIR/postgres -D $PG_DATADIR"

